### ISSUE TITLE
ggsave support

### ISSUE THREAD

**Issue by GuangchuangYu** [wilkox/ggwrap#1]
<https://github.com/wilkox/ggwrap/blob/master/R/ggwrap.R#L58>

why not just return `pgrob` and `ggsave` will support the output object directly.

What you need is to set class attribute of the `pgrob` and write corresponding `print` method if you want the output object to be displayed interactively.

**Comment by wilkox** [comment]
Ah, I never knew `ggsave` supports any `grid` object. Thanks for the suggestion!
